springdoc:
  swagger-ui:
    path: /api-doc
    
server:
  port: 5000
  
feign:
  client:
    config:
      default:        
        error-decoder: com.backend.devstest.config.RetryerErrorDecoder 
        connectTimeout: 120000
        readTimeout: 60000
        loggerLevel: basic     